name: snakemake-workflow-catalog
channels:
  - conda-forge
  - bioconda
dependencies:
  - jinja2=3.1.4
  - pygithub=2.5.0
  - gitpython=3.1.43
  - snakemake=8.25.5
  - snakefmt=0.10.2
  - python=3.12.8
  - ratelimit=2.2.1
  - mdutils=1.6.0
  - sphinx=7.2.6
  - sphinxawesome-theme=5.2.0
  - sphinx-design=0.6.1
  - myst-parser=4.0.1
  - pip
  - pip:
    - sphinxcontrib-jquery
    - sphinx-datatables
