name: Test

on:
  pull_request:
    branches: [main, dev]

jobs:
  generate-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: deployment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      # Test the normal catalog generation but restrict to first three repos for speed
      - name: test-generate-catalog
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OFFSET: 0
          N_REPOS: 3
          LATEST_COMMIT: 7
        run: |
          python scripts/generate-catalog.py

      # Test specific repo, ensuring that the whole catalog generation script is
      # executed, in case the first repos above are skipped because it contains no
      # updates or no real snakemake workflow
      - name: test-generate-catalog-specific-repo
        shell: bash -l {0}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TEST_REPO: snakemake-workflows/dna-seq-varlociraptor
        run: |
          python scripts/generate-catalog.py

  cleanup-catalog:
    runs-on: ubuntu-latest
    needs: generate-catalog
    steps:
      - uses: actions/checkout@v4

      - name: deployment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      # Test the cleanup script
      - name: cleanup-catalog
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OFFSET: 0
          N_REPOS: 3
        run: |
          python scripts/cleanup-catalog.py
